### ISSUE TITLE
not an issue: x16s

### ISSUE THREAD

**Issue by a37k** [nemosminer/ccminernevermore#2]
Please see: https://github.com/brian112358/nevermore-miner-x16s, a x16s version of this fork.

Donation pool causes miner to stall as the dev pool stratum is not reachable for some reason.

**Comment by nemosminer** [comment]
this is that version............ mine is forked from his....
I have Removed Dev fee and recompiled Windows binaries 
working on hash rate fluctuation at the moement

**Comment by a37k** [comment]
And some occasional termination on it's own on one rig with two NV gpus. 1060 + 1080ti. This happens a lot. Still talking about x16s fork BTW.

**Comment by nemosminer** [comment]
a37k no its running perfectly on all my rigs i have 2 x 8x10603gb 1x6x1070 2x6x1070ti 2x6x1080ti

im talking about https://github.com/nemosminer/ccminernevermore BTW x16r (not x16s lol)

**Comment by nemosminer** [comment]
thanks @a37k
